language: java

jdk:
  - oraclejdk8

services:
  - docker

dist: trusty

before_install: [ ]

install:
  - mvn install

script:
  - make docker-build

cache:
  directories:
    - $HOME/.m2
    - BuildTools