name: EnchantmentsEnhance
version: 1.2.1
description: This is a Black Desert Online Style of Enchantment enhancing
author: Feier

main: me.bukkit.main.Main
database: false
website: https://github.com/HealPot


commands:
    enhance:
        usage: /<command>
        description: use /enhance to upgrade your armor.
                     use /enhance version to check the version.
                     use /enhance maxRate to check the success rate.
        
permissions:
    enhancement.*:
        description: Gives access to all enhancement permissions and commands
    enhancement.armor:
        description: Allows you to enhance diamond armors
        default: true
    enhancement.weapon:
        description: Allows you to enhance diamond weapons
        default: true
    enhancement.version:
        description: Allows you to see the version of the plugin
        default: op
    enhancement.chance:
        description: Allows you to check the success rate of item that you are holding
        default: true