language: en_us
#supported language: zh_cn, en_us.

lore:
  bound: Tradeable
#supported bound type: Tradeable, Untradeable
#Tradeable: keep-item-on-death, personal trading is allowed.
#Untradeable: keep-item-on-death, cannot be stored, cannot be dropped.
  sendBoundingMessage: false
dropConcWeapon:
  ratePerBlock: 0.01
#In range of 0.01 means player will possibly get 1 conc Weapon out of 100 ores mined.
  block:
    - DIAMOND_ORE
    - EMERALD_ORE
    - EMERALD_ORE
    - GLOWING_REDSTONE_ORE
    - GOLD_ORE
    - IRON_ORE
    - LAPIS_ORE
    - QUARTZ_ORE
    - REDSTONE_ORE
dropConcArmor:
  ratePerBlock: 0.01
  block:
    - LOG
dropWeaponNArmor:
  fishing:
    enabled: true
    ratePerFish: 0.05
  allMob:
    enabled: true
    ratePerKill: 0.01
fireworkDelay: 0
fireworkCount: 1

FirstPhaseStarts: 7
SecondPhaseStarts: 15
DowngradePhaseStarts: 17

enhance:
  0:
    baseChance: 100
    chanceIncreasePerFailstack: -1
    maximumFailstackApplied: -1
    failstackGainedPerFail: -1
    costToForceEnchant: -1
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: ""
  1:
    baseChance: 100
    chanceIncreasePerFailstack: -1
    maximumFailstackApplied: -1
    failstackGainedPerFail: -1
    costToForceEnchant: -1
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+1"
  2:
    baseChance: 100
    chanceIncreasePerFailstack: -1
    maximumFailstackApplied: -1
    failstackGainedPerFail: -1
    costToForceEnchant: -1
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+2"
  3:
    baseChance: 100
    chanceIncreasePerFailstack: -1
    maximumFailstackApplied: -1
    failstackGainedPerFail: -1
    costToForceEnchant: -1
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+3"
  4:
    baseChance: 100
    chanceIncreasePerFailstack: -1
    maximumFailstackApplied: -1
    failstackGainedPerFail: -1
    costToForceEnchant: -1
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+4"
  5:
    baseChance: 100
    chanceIncreasePerFailstack: -1
    maximumFailstackApplied: -1
    failstackGainedPerFail: -1
    costToForceEnchant: -1
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+5"
  6:
    baseChance: 100
    chanceIncreasePerFailstack: -1
    maximumFailstackApplied: -1
    failstackGainedPerFail: -1
    costToForceEnchant: -1
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+6"
  7:
    baseChance: 20
    chanceIncreasePerFailstack: 2.5
    maximumFailstackApplied: 13
    failstackGainedPerFail: 1
    costToForceEnchant: 3
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+7"
  8:
    baseChance: 17.5
    chanceIncreasePerFailstack: 2.0
    maximumFailstackApplied: 14
    failstackGainedPerFail: 1
    costToForceEnchant: 4
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+8"
  9:
    baseChance: 15
    chanceIncreasePerFailstack: 1.5
    maximumFailstackApplied: 15
    failstackGainedPerFail: 1
    costToForceEnchant: 5
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+9"
  10:
    baseChance: 12.5
    chanceIncreasePerFailstack: 1.25
    maximumFailstackApplied: 16
    failstackGainedPerFail: 1
    costToForceEnchant: 7
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+10"
  11:
    baseChance: 10
    chanceIncreasePerFailstack: 0.75
    maximumFailstackApplied: 18
    failstackGainedPerFail: 1
    costToForceEnchant: 9
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+11"
  12:
    baseChance: 7.5
    chanceIncreasePerFailstack: 0.63
    maximumFailstackApplied: 20
    failstackGainedPerFail: 1
    costToForceEnchant: 12
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+12"
  13:
    baseChance: 5
    chanceIncreasePerFailstack: 0.5
    maximumFailstackApplied: 25
    failstackGainedPerFail: 1
    costToForceEnchant: 15
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+13"
  14:
    baseChance: 2.5
    chanceIncreasePerFailstack: 0.5
    maximumFailstackApplied: 25
    failstackGainedPerFail: 1
    costToForceEnchant: 18
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+14"
  15:
    baseChance: 15
    chanceIncreasePerFailstack: 1.5
    maximumFailstackApplied: 25
    failstackGainedPerFail: 2
    costToForceEnchant: 22
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+15"
  16:
    baseChance: 7.5
    chanceIncreasePerFailstack: 0.75
    maximumFailstackApplied: 35
    failstackGainedPerFail: 3
    costToForceEnchant: 27
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "PRI"
  17:
    baseChance: 5.0
    chanceIncreasePerFailstack: 0.5
    maximumFailstackApplied: 44
    failstackGainedPerFail: 4
    costToForceEnchant: 45
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "DUO"
  18:
    baseChance: 2.0
    chanceIncreasePerFailstack: 0.25
    maximumFailstackApplied: 90
    failstackGainedPerFail: 5
    costToForceEnchant: -1
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "TRI"
  19:
    baseChance: 1.5
    chanceIncreasePerFailstack: 0.25
    maximumFailstackApplied: 124
    failstackGainedPerFail: 6
    costToForceEnchant: -1
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "TET"
  20:
    baseChance: -1
    chanceIncreasePerFailstack: -1
    maximumFailstackApplied: -1
    failstackGainedPerFail: -1
    costToForceEnchant: -1
    fireworkIfSuccessful: false
    fireworkRounds: -1
    name: "PEN"