############################################################
# +------------------------------------------------------+ #
# |                       Notes                          | #
# +------------------------------------------------------+ #
############################################################

# If you want to use special characters in this document, such as accented letters, you MUST save the file as UTF-8, not ANSI.
# If you receive an error when EnchantmentsEnhance loads, ensure that:
#   - No tabs are present: YAML only allows spaces
#   - Indents are correct: YAML hierarchy is based entirely on indentation
#   - You have "escaped" all apostrophes in your text: If you want to write "don't", for example, write "don''t" instead (note the doubled apostrophe)
#   - Text with symbols is enclosed in single or double quotation marks

# If you have encountered any problems, use: https://github.com/HealPotion/EnchantmentsEnhance/issues

############################################################
# +------------------------------------------------------+ #
# |                  EnchantmentsEnhance                 | #
# +------------------------------------------------------+ #
############################################################

# Supported language: ZH_CN, EN_US.
language: EN_US

# Set true to disable vanilla enchanting table and when someone use it, right click on it will open enhance menu.
enableVanillaEnchant: false

# Set true to enable support for stacked mob drop.
enableStackMob: false

# Lore is the additional attribution that is added to the enhanced item.
lore:
  # Supported bound type: tradeable, untradeable.
  # tradeable: keep-item-on-death, personal trading is allowed.
  # untradeable: keep-item-on-death, cannot be stored, cannot be dropped.
  bound: tradeable
  # Do you want to notify the player when the item becomes bounded?
  sendBoundingMessage: false

# Life Skills consist of various tasks. Black stones will be rewarded by performing any of these tasks.
lifeskill:
  # What ore counts as mining blocks?
  mining:
    - DIAMOND_ORE
    - EMERALD_ORE
    - EMERALD_ORE
    - GLOWING_REDSTONE_ORE
    - GOLD_ORE
    - IRON_ORE
    - LAPIS_ORE
    - QUARTZ_ORE
    - REDSTONE_ORE
  # What block counts as chopping blocks?
  chopping:
    # LOG includes all the tree blocks.
    - LOG
  fishing:
    # What actions counts as fishing?
    - CAUGHT_FISH
    # - BITE
    # - CAUGHT_ENTITY
    # - FAILED_ATTEMPT
    # - FISHING
    # - IN_GROUND
# What entity will reward black stones when killed?
  killing:
    - MONSTER
    # - ANIMALS
# What entity will reward black stones when bred?
  breeding:
    - ANIMALS
# What item will reward black stones when smelt?
  smelting:
    - ITEM

# Stones ID
# 0 = weapon stone
# 1 = armor stone
# 2 = concentrated weapon stone
# 3 = concentrated armor stone
# In range of 0.01 means player will possibly get 1 out of 100 lifeskill event.
reward:
  mining:
    chance: 0.03
    drops:
      - 0
      - 1
      - 2
      - 3
  chopping:
    chance: 0.02
    drops:
      - 0
      - 1
      - 2
      - 3
  fishing:
    chance: 0.05
    drops:
      - 0
      - 1
  killing:
    chance: 0.01
    drops:
      - 0
      - 1
      - 2
      - 3
  breeding:
    chance: 0.08
    drops:
      - 0
      - 1
      - 2
      - 3
  smelting:
    chance: 0.01
    drops:
      - 0
      - 1
      - 2
      - 3

# When enhancement is succeed, it controls the firework delay launch.
fireworkDelay: 0
# How many firework will be launched.
fireworkCount: 1

# Material Reference: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
material:
  # stoneTypes is the ID of the item in-game.
  stoneTypes:
    #0 weapon stone
    - GHAST_TEAR
    #1 armor stone
    - GOLD_NUGGET
    #2 concentrated weapon stone
    - SUGAR
    #3 concentrated armor stone
    - GLOWSTONE_DUST
  # List of Armor.
  armor:
    - DIAMOND_HELMET
    - DIAMOND_CHESTPLATE
    - DIAMOND_LEGGINGS
    - DIAMOND_BOOTS
    - IRON_HELMET
    - IRON_CHESTPLATE
    - IRON_LEGGINGS
    - IRON_BOOTS
    - GOLD_HELMET
    - GOLD_CHESTPLATE
    - GOLD_LEGGINGS
    - GOLD_BOOTS
    - LEATHER_HELMET
    - LEATHER_CHESTPLATE
    - LEATHER_LEGGINGS
    - LEATHER_BOOTS
    - CHAINMAIL_HELMET
    - CHAINMAIL_CHESTPLATE
    - CHAINMAIL_LEGGINGS
    - CHAINMAIL_BOOTS
  # List of weapon.
  weapon:
    - DIAMOND_SWORD
    - GOLD_SWORD
    - STONE_SWORD
    - WOOD_SWORD
    - DIAMOND_AXE
    - GOLD_AXE
    - STONE_AXE
    - WOOD_AXE
    - IRON_SWORD
    - IRON_AXE
    - WOOD_AXE

# Accessory slots.
# Player will place their items to those position in order to use their accessories.
# Player Inventory Slot Reference: https://github.com/HealPotion/EnchantmentsEnhance/blob/master/.images/player_inventory.png
accessory:
  left_ring: 9
  right_ring: 10
  left_earring: 18
  right_earring: 19
  necklace: 27
  belt:  28

# @Deprecated Phase when the enhancement is not guaranteed success.
FirstPhaseStarts: 7
# Phase when the enhancement takes concentrated stones.
SecondPhaseStarts: 15
# Phase when the item will downgrade if the enhancement is failed.
DowngradePhaseStarts: 17

# Vanilla Enchantments Reference: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/enchantments/Enchantment.html#
enhance:
  0:
    # The success rate of item at the level.
    baseChance: 100
    # Chance increase per failstack you have.
    chanceIncreasePerFailstack: -1
    # The maximum failstack applied to the enhancement.
    maximumFailstackApplied: -1
    # Failstack gained from failing an enhancement at this level.
    failstackGainedPerFail: -1
    # Cost of black stone to enhance the item.
    costToForceEnchant: -1
    # Enable or disable firework.
    fireworkIfSuccessful: true
    # Rounds of firework.
    fireworkRounds: 1
    # Prefix of the item
    name: "+0"
    # Applying enchantment.
    enchantments: []
  1:
    baseChance: 100
    chanceIncreasePerFailstack: -1
    maximumFailstackApplied: -1
    failstackGainedPerFail: -1
    costToForceEnchant: -1
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+1"
    enchantments:
      WEAPON:
         - DAMAGE_ALL:1
         - Assassin:1
      ARMOR:
         - PROTECTION_ENVIRONMENTAL:1
  2:
    baseChance: 100
    chanceIncreasePerFailstack: -1
    maximumFailstackApplied: -1
    failstackGainedPerFail: -1
    costToForceEnchant: -1
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+2"
    enchantments:
      WEAPON:
         - DAMAGE_ALL:2
         - Kill_Confirm:1
      ARMOR:
         - PROTECTION_ENVIRONMENTAL:2
  3:
    baseChance: 100
    chanceIncreasePerFailstack: -1
    maximumFailstackApplied: -1
    failstackGainedPerFail: -1
    costToForceEnchant: -1
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+3"
    enchantments:
      WEAPON:
         - DAMAGE_ALL:3
         - Hex:1
      ARMOR:
         - PROTECTION_ENVIRONMENTAL:3
  4:
    baseChance: 100
    chanceIncreasePerFailstack: -1
    maximumFailstackApplied: -1
    failstackGainedPerFail: -1
    costToForceEnchant: -1
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+4"
    enchantments:
      WEAPON:
         - DAMAGE_ALL:4
         - Riftslayer:1
      ARMOR:
         - PROTECTION_ENVIRONMENTAL:4
  5:
    baseChance: 100
    chanceIncreasePerFailstack: -1
    maximumFailstackApplied: -1
    failstackGainedPerFail: -1
    costToForceEnchant: -1
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+5"
    enchantments:
      WEAPON:
         - DAMAGE_ALL:5
         - Demon_Siphon:1
      ARMOR:
         - PROTECTION_ENVIRONMENTAL:5
  6:
    baseChance: 100
    chanceIncreasePerFailstack: -1
    maximumFailstackApplied: -1
    failstackGainedPerFail: -1
    costToForceEnchant: -1
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+6"
    enchantments:
      WEAPON:
         - DAMAGE_ALL:6
         - Lifesteal:1
      ARMOR:
         - PROTECTION_ENVIRONMENTAL:5
  7:
    baseChance: 20
    chanceIncreasePerFailstack: 2.5
    maximumFailstackApplied: 13
    failstackGainedPerFail: 1
    costToForceEnchant: 3
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+7"
    enchantments:
      WEAPON:
         - DAMAGE_ALL:7
      ARMOR:
         - PROTECTION_ENVIRONMENTAL:5
  8:
    baseChance: 17.5
    chanceIncreasePerFailstack: 2.0
    maximumFailstackApplied: 14
    failstackGainedPerFail: 1
    costToForceEnchant: 4
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+8"
    enchantments:
      WEAPON:
         - DAMAGE_ALL:8
      ARMOR:
         - PROTECTION_ENVIRONMENTAL:5
  9:
    baseChance: 15
    chanceIncreasePerFailstack: 1.5
    maximumFailstackApplied: 15
    failstackGainedPerFail: 1
    costToForceEnchant: 5
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+9"
    enchantments:
      WEAPON:
         - DAMAGE_ALL:9
      ARMOR:
         - PROTECTION_ENVIRONMENTAL:5
  10:
    baseChance: 12.5
    chanceIncreasePerFailstack: 1.25
    maximumFailstackApplied: 16
    failstackGainedPerFail: 1
    costToForceEnchant: 7
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+10"
    enchantments:
      WEAPON:
         - DAMAGE_ALL:10
      ARMOR:
         - PROTECTION_ENVIRONMENTAL:5
  11:
    baseChance: 10
    chanceIncreasePerFailstack: 0.75
    maximumFailstackApplied: 18
    failstackGainedPerFail: 1
    costToForceEnchant: 9
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+11"
    enchantments:
      WEAPON:
         - DAMAGE_ALL:11
      ARMOR:
         - PROTECTION_ENVIRONMENTAL:5
  12:
    baseChance: 7.5
    chanceIncreasePerFailstack: 0.63
    maximumFailstackApplied: 20
    failstackGainedPerFail: 1
    costToForceEnchant: 12
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+12"
    enchantments:
      WEAPON:
         - DAMAGE_ALL:12
      ARMOR:
         - PROTECTION_ENVIRONMENTAL:5
  13:
    baseChance: 5
    chanceIncreasePerFailstack: 0.5
    maximumFailstackApplied: 25
    failstackGainedPerFail: 1
    costToForceEnchant: 15
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+13"
    enchantments:
      WEAPON:
         - DAMAGE_ALL:13
      ARMOR:
         - PROTECTION_ENVIRONMENTAL:5
  14:
    baseChance: 2.5
    chanceIncreasePerFailstack: 0.5
    maximumFailstackApplied: 25
    failstackGainedPerFail: 1
    costToForceEnchant: 18
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+14"
    enchantments:
      WEAPON:
         - DAMAGE_ALL:14
      ARMOR:
         - PROTECTION_ENVIRONMENTAL:5
  15:
    baseChance: 15
    chanceIncreasePerFailstack: 1.5
    maximumFailstackApplied: 25
    failstackGainedPerFail: 2
    costToForceEnchant: 22
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+15"
    enchantments:
      WEAPON:
         - DAMAGE_ALL:15
      ARMOR:
         - PROTECTION_ENVIRONMENTAL:5
  16:
    baseChance: 7.5
    chanceIncreasePerFailstack: 0.75
    maximumFailstackApplied: 35
    failstackGainedPerFail: 3
    costToForceEnchant: 27
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "PRI"
    enchantments:
      WEAPON:
         - DAMAGE_ALL:17
      ARMOR:
         - PROTECTION_ENVIRONMENTAL:5
  17:
    baseChance: 5.0
    chanceIncreasePerFailstack: 0.5
    maximumFailstackApplied: 44
    failstackGainedPerFail: 4
    costToForceEnchant: 45
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "DUO"
    enchantments:
      WEAPON:
         - DAMAGE_ALL:19
      ARMOR:
         - PROTECTION_ENVIRONMENTAL:5
  18:
    baseChance: 2.0
    chanceIncreasePerFailstack: 0.25
    maximumFailstackApplied: 90
    failstackGainedPerFail: 5
    costToForceEnchant: -1
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "TRI"
    enchantments:
      WEAPON:
         - DAMAGE_ALL:21
      ARMOR:
         - PROTECTION_ENVIRONMENTAL:5
  19:
    baseChance: 1.5
    chanceIncreasePerFailstack: 0.25
    maximumFailstackApplied: 124
    failstackGainedPerFail: 6
    costToForceEnchant: -1
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "TET"
    enchantments:
      WEAPON:
         - DAMAGE_ALL:23
      ARMOR:
         - PROTECTION_ENVIRONMENTAL:5
  20:
    baseChance: -1
    chanceIncreasePerFailstack: -1
    maximumFailstackApplied: -1
    failstackGainedPerFail: -1
    costToForceEnchant: -1
    fireworkIfSuccessful: false
    fireworkRounds: -1
    name: "PEN"
    enchantments:
      WEAPON:
         - DAMAGE_ALL:25
         - Lifesteal:3
         - Assassin:3
         - Kill_Confirm:3
         - Hex:3
         - Riftslayer:1
         - Demon_Siphon:3
         - Angry_Birds:5
         - Curse:4
         - Crushing:5
         - Execute:5
         - Purge:4
         - Divine:3
         - Plunder:1
         - Mischief:3
         - Disarm:3
         - Thief:3
         - Reborn:3
         - Web_Trap:3
         - Reversal:3
         - Endless:1

      ARMOR:
         - PROTECTION_ENVIRONMENTAL:5
         - Dodge:5
         - Blessed:3
         - Demonic_Aura:1
         - Stealth:4
         - Aegis:5
         - Platemail:1
         - Pyromanic:5
         - Flame_Cloak:3
         - Spiked:2
         - Shadowstep:3
         - Tamer:1
         - Wolves:1
         - Repel:3
         - Horse_Rider:1
         - Paralyze:2
         - Farmer:1
         - Feather_Fall:1
         - Jump:3
         - Speed:3
         - Batvision:1
         - Eyepatch:1
         - Swimmer:3
         - Endless:1
         - Health_Boost:3
         - Molten:1
         - Immolation:5
         - Strength:3
         - Reinforced:5
         - Suicide:1
         - Batman:3
         - Necromancer:5

# Reform an item grade.
weaponGrade:
  0:
    name: ""
    enchantments: []
  1:
    name: "Crimson Flame"
    enchantments:
        - FIRE_ASPECT:1
  2:
    name: "Destruction"
    enchantments:
        - DAMAGE_ALL:1
  3:
    name: "Temptation"
    enchantments:
        - LOOT_BONUS_MOBS:1
  4:
    name: "Ultimate"
    enchantments:
        - DAMAGE_ALL:2
        - DURABILITY:2
  5:
    name: "Kzarka"
    enchantments:
        - DAMAGE_ALL:3
        - DURABILITY:3
  6:
    name: "Dandelion"
    enchantments:
        - DAMAGE_ARTHROPODS:3
        - DAMAGE_UNDEAD:3
        - DURABILITY:3
        - LOOT_BONUS_MOBS:3
armorGrade:
  0:
    name: ""
    enchantments: []
  1:
    name: "Agility"
    enchantments:
        - PROTECTION_FALL:1
  2:
    name: "Intimidation"
    enchantments:
        - THORNS:1
  3:
    name: "Iron Wall"
    enchantments:
        - PROTECTION_EXPLOSIONS:1
  4:
    name: "Ultimate"
    enchantments:
        - PROTECTION_ENVIRONMENTAL:2
        - DURABILITY:2
name:
  axe: "Ain Axe"
  sword: "Great Sword"
  bow: "Long Bow"
pickaxe:
  0:
    name: "Broken Pickaxe"
    enchantments: []
  1:
    name: "Improved Pickaxe"
    enchantments:
      - DURABILITY:1
  2:
    name: "Sharp Pickaxe"
    enchantments:
      - DIG_SPEED:1
  3:
    name: "Steel Pickaxe"
    enchantments:
      - DIG_SPEED:1
      - DURABILITY:1
  4:
    name: "Lucky Steel Pickaxe"
    enchantments:
      - DIG_SPEED:3
      - DURABILITY:3
      - LOOT_BONUS_BLOCKS:1
  5:
    name: "Magic Pickaxe"
    enchantments:
      - DIG_SPEED:4
      - DURABILITY:4
  6:
    name: "Lucky Magic Pickaxe"
    enchantments:
      - DIG_SPEED:5
      - DURABILITY:5
      - LOOT_BONUS_BLOCKS:2
  7:
    name: "Master Pickaxe"
    enchantments:
      - DIG_SPEED:6
      - DURABILITY:6
  8:
    name: "Lucky Master Pickaxe"
    enchantments:
      - DIG_SPEED:7
      - DURABILITY:7
      - LOOT_BONUS_BLOCKS:3
  9:
    name: "Lucky Shining Magic Pickaxe"
    enchantments:
      - DIG_SPEED:8
      - DURABILITY:8
      - LOOT_BONUS_BLOCKS:4
  10:
    name: "Lucky Shining Master Pickaxe"
    enchantments:
      - DIG_SPEED:10
      - DURABILITY:10
      - LOOT_BONUS_BLOCKS:5
fishing rod:
  0:
    name: "Broken Fishing Rod"
    enchantments: []
  1:
    name: "Fishing Rod"
    enchantments:
      - DURABILITY:1
  2:
    name: "Old Fishing Rod"
    enchantments:
      - LUCK:1
  3:
    name: "Thick Fishing Rod"
    enchantments:
      - LUCK:1
      - DURABILITY:1
  4:
    name: "Steel Fishing Rod"
    enchantments:
      - LUCK:3
      - LURE:3
      - DURABILITY:3
  5:
    name: "Triple-Float Rod"
    enchantments:
      - LUCK:3
      - LURE:3
      - DURABILITY:4
  6:
    name: "Lucky Silver Fishing Rod"
    enchantments:
      - LUCK:3
      - LURE:4
      - DURABILITY:4
  7:
    name: "Lucky Golden Fishing Rod"
    enchantments:
      - LUCK:4
      - LURE:4
      - DURABILITY:4
  8:
    name: "Splendid Golden Fishing Rod"
    enchantments:
      - LUCK:4
      - LURE:4
      - DURABILITY:5
  9:
    name: "Fancy Golden Fishing Rod"
    enchantments:
      - LUCK:4
      - LURE:4
      - DURABILITY:5
  10:
    name: "Artisan Fishing Rod"
    enchantments:
      - LUCK:5
      - LURE:5
      - DURABILITY:5
        